# Generated by Django 5.0 on 2023-12-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sneaksaver", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cleanservice",
            name="service_price",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
