# Generated by Django 4.2.7 on 2024-01-10 16:18

from django.db import migrations, models
import sneaksaver.utils


class Migration(migrations.Migration):
    dependencies = [
        ("sneaksaver", "0003_booking_description_booking_email_booking_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "service_price",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="/static/images/b2.jpg",
                        null=True,
                        upload_to=sneaksaver.utils.upload_location,
                    ),
                ),
            ],
        ),
    ]
