# Generated by Django 4.2.7 on 2024-01-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sneaksaver", "0005_rename_service_price_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
