# Generated by Django 4.2.7 on 2024-01-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sneaksaver", "0006_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
