# Generated by Django 4.2.7 on 2024-01-10 17:43

from django.db import migrations, models
import sneaksaver.utils


class Migration(migrations.Migration):
    dependencies = [
        ("sneaksaver", "0007_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default_product.jpg",
                null=True,
                upload_to=sneaksaver.utils.upload_location,
            ),
        ),
    ]
