# Generated by Django 4.2.7 on 2024-01-26 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sneaksaver', '0013_shoemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sneaksaver.shoemodel'),
        ),
    ]
