# Generated by Django 4.2.7 on 2024-02-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaksaver', '0014_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='agent_reply',
            field=models.TextField(null=True),
        ),
    ]
