# Generated by Django 4.2.7 on 2024-01-25 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sneaksaver', '0010_product_date_alter_booking_date_alter_contact_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_count', models.IntegerField(default=0)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sneaksaver.product')),
            ],
        ),
        migrations.CreateModel(
            name='CleanServiceSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_count', models.IntegerField(default=0)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sneaksaver.cleanservice')),
            ],
        ),
    ]
