# Generated by Django 4.2.7 on 2024-01-27 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0003_faqs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQs',
            new_name='FrequentlyAskedQuestion',
        ),
    ]
