# Generated by Django 4.2.7 on 2024-01-10 13:20

from django.db import migrations, models
import user.utils


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_profile_first_name_profile_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default.jpg",
                null=True,
                upload_to=user.utils.upload_location,
            ),
        ),
    ]
